### PR TITLE
Add item-per-item iteration so that users don't need to manage "pages" of results

### PR DESCRIPTION
**Pull request by HaraldJoerg**
This pull request is motivated by the CPAN Pull Request Challenge, http://cpan-prc.org/.
It is a suggestion for an iteration over individual items instead of "pages".  Using this iteration, the caller does not need to manage API calls to fetch more pages of results.
The first three commits are small fixes to the docs and tests, which are actually unrelated to pagination.  The fourth contains the basic iteration mechanism plus the implementation for the submodule Net::GitHub::V3::Issues, and documentation for this submodule, as well as a first test script.
The other submodules are pretty straightforward and will follow, but I've a different assignment for the rest of the week, and maybe you can review the proposal from what I've done with Issues.pm.

Unfortunately, I am not a regular user of this module, so I'd welcome pointers to typical workflows or relevant reverse dependencies which I could add as tests.

### CODE REVIEW

**Comment by fayland** [comment]
Hello. thanks for the patching.

overall it looks very good even I didn't test it yet.

just wondering why we need close_*?

thanks

**Comment by HaraldJoerg** [comment]
Hello Fayland,

you write:

> Hello. thanks for the patching.
>
> overall it looks very good even I didn't test it yet.

Fine! I'll complete the other submodules next week.

> just wondering why we need close_*?

I added these out of old habits - it depends on how the module is used.

For command line scripts based on Net::GitHub you don't need close_*.
But if you want to embed it into a webserver, then the "open" queries
would hang around forever.  Not only would the result sets pile up in
memory, but they would also prevent a user to see the first issue if
they didn't walk through the complete queue of issues the day before.

I'll add that to the documentation.

An alternative would be to go object oriented and create result objects
(similar to what Pithub::Result does).  In that case, the query results
would be dropped automatically when the result object goes out of scope.
I could do this if you prefer it.  It needs some refactoring, though,
because each result set object would need to be able to fetch new pages
from the API.

By the way: If you call close_issue(...) and then next_issue() again,
you don't consume GitHub API calls.  The code will fetch the first page,
which should still be in the cache.
-- 
Cheers,
haj

**Comment by fayland** [comment]
hi, thanks for the PR and it looks good. I'll merge it and release after you fixed the minor docs issue.

**Comment by HaraldJoerg** [comment]
A section whether, when and why close_xxx methods may be needed has been included in lib/Net/GitHub/V3.pm, next to the existing section about pagination.

**What is still open is pagination of search results** (Search.pm), which has easy and tricky parts.  It is easy to derive the next_ and close_methods from what is there.  The JSON result comes as a hashref instead of an arrayref, so we could iterate over the list elements of the 'item' key with a few extra lines.  However, the hash response is there for a reason: In addition to the items, it contains information about the total number of hits, and whether there was a timeout on the server side.  I consider this information vital: Iterating over millions of hits is a very bad idea, and interpreting incomplete results is a very bad idea as well.  In both cases, the caller needs to adjust his query.

So, a possible approach would be to die if the server reports incomplete results, and also to die if the total number of hits exceed a defined threshold (but which threshold is good enough?  Should be configurable on creation of the Search object...).

A second approach would store the two values after the first next_repository (or next_issue, or...) in the Search object.  The user would need to call next_ once before he can evaluate the values and maybe abort the iteration.

As a third approach, we could add total_xxx and is_complete_xxx methods to each of issues, repositories, code and users.

And, of course, we could leave searching as it is.  The page-per-page iteration works just fine, and the two values are returned in the page response so that the caller can (must!) check the.

Do you have any preferences?  Maybe we should followup in another pull request?

**Comment by fayland** [comment]
yes. it's good enough for now. we can leave search first. thanks

**Comment by fayland** [comment]
I just shipped 0.94 to CPAN. thanks for your work!

**Pull request merged**
